version: 2

jobs:
  build:
    working_directory: /home/agent/build
    docker:
      - image: docksal/ci-agent:edge-php
    environment:
       BASH_ENV: /home/agent/.bashrc  # Tell CircleCI where to read the shared build environment variables from
    steps:
      - checkout
      - run:
          name: Configure local build environment
          command: |
            touch $BASH_ENV
            echo 'source build-env' >> $BASH_ENV
      - run:
          name: Sandbox provisioning
          command: |
            ssh docker-host "if [ ! -d $REMOTE_BUILD_DIR ]; then mkdir -p $REMOTE_BUILD_DIR; fi"
            build-init
            slack "Started sandbox build for branch *${GIT_BRANCH_NAME}*"
            ssh docker-host "cd $REMOTE_BUILD_DIR && fin init"
            slack "Completed sandbox build for branch *${GIT_BRANCH_NAME}*:\n<http://${DOMAIN}|http://${DOMAIN}>"
